import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const countries = [
  { code: 'AF', name: 'Afghanistan', flagEmoji: '🇦🇫', phoneCode: '+93', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'AL', name: 'Albania', flagEmoji: '🇦🇱', phoneCode: '+355', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 7 },
  { code: 'DZ', name: 'Algeria', flagEmoji: '🇩🇿', phoneCode: '+213', hasDelivery: true, deliveryCost: 30.00, deliveryDays: 10 },
  { code: 'AD', name: 'Andorra', flagEmoji: '🇦🇩', phoneCode: '+376', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 5 },
  { code: 'AO', name: 'Angola', flagEmoji: '🇦🇴', phoneCode: '+244', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'AG', name: 'Antigua and Barbuda', flagEmoji: '🇦🇬', phoneCode: '+1268', hasDelivery: true, deliveryCost: 35.00, deliveryDays: 12 },
  { code: 'AR', name: 'Argentina', flagEmoji: '🇦🇷', phoneCode: '+54', hasDelivery: true, deliveryCost: 40.00, deliveryDays: 15 },
  { code: 'AM', name: 'Armenia', flagEmoji: '🇦🇲', phoneCode: '+374', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'AU', name: 'Australia', flagEmoji: '🇦🇺', phoneCode: '+61', hasDelivery: true, deliveryCost: 35.00, deliveryDays: 10 },
  { code: 'AT', name: 'Austria', flagEmoji: '🇦🇹', phoneCode: '+43', hasDelivery: true, deliveryCost: 15.00, deliveryDays: 3 },
  { code: 'AZ', name: 'Azerbaijan', flagEmoji: '🇦🇿', phoneCode: '+994', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'BS', name: 'Bahamas', flagEmoji: '🇧🇸', phoneCode: '+1242', hasDelivery: true, deliveryCost: 35.00, deliveryDays: 12 },
  { code: 'BH', name: 'Bahrain', flagEmoji: '🇧🇭', phoneCode: '+973', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 7 },
  { code: 'BD', name: 'Bangladesh', flagEmoji: '🇧🇩', phoneCode: '+880', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 6 },
  { code: 'BB', name: 'Barbados', flagEmoji: '🇧🇧', phoneCode: '+1246', hasDelivery: true, deliveryCost: 35.00, deliveryDays: 12 },
  { code: 'BY', name: 'Belarus', flagEmoji: '🇧🇾', phoneCode: '+375', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'BE', name: 'Belgium', flagEmoji: '🇧🇪', phoneCode: '+32', hasDelivery: true, deliveryCost: 15.00, deliveryDays: 3 },
  { code: 'BZ', name: 'Belize', flagEmoji: '🇧🇿', phoneCode: '+501', hasDelivery: true, deliveryCost: 35.00, deliveryDays: 12 },
  { code: 'BJ', name: 'Benin', flagEmoji: '🇧🇯', phoneCode: '+229', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'BT', name: 'Bhutan', flagEmoji: '🇧🇹', phoneCode: '+975', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'BO', name: 'Bolivia', flagEmoji: '🇧🇴', phoneCode: '+591', hasDelivery: true, deliveryCost: 40.00, deliveryDays: 15 },
  { code: 'BA', name: 'Bosnia and Herzegovina', flagEmoji: '🇧🇦', phoneCode: '+387', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 5 },
  { code: 'BW', name: 'Botswana', flagEmoji: '🇧🇼', phoneCode: '+267', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'BR', name: 'Brazil', flagEmoji: '🇧🇷', phoneCode: '+55', hasDelivery: true, deliveryCost: 45.00, deliveryDays: 18 },
  { code: 'BN', name: 'Brunei', flagEmoji: '🇧🇳', phoneCode: '+673', hasDelivery: true, deliveryCost: 30.00, deliveryDays: 10 },
  { code: 'BG', name: 'Bulgaria', flagEmoji: '🇧🇬', phoneCode: '+359', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 5 },
  { code: 'BF', name: 'Burkina Faso', flagEmoji: '🇧🇫', phoneCode: '+226', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'BI', name: 'Burundi', flagEmoji: '🇧🇮', phoneCode: '+257', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'KH', name: 'Cambodia', flagEmoji: '🇰🇭', phoneCode: '+855', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'CM', name: 'Cameroon', flagEmoji: '🇨🇲', phoneCode: '+237', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'CA', name: 'Canada', flagEmoji: '🇨🇦', phoneCode: '+1', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 5 },
  { code: 'CV', name: 'Cape Verde', flagEmoji: '🇨🇻', phoneCode: '+238', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'CF', name: 'Central African Republic', flagEmoji: '🇨🇫', phoneCode: '+236', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'TD', name: 'Chad', flagEmoji: '🇹🇩', phoneCode: '+235', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'CL', name: 'Chile', flagEmoji: '🇨🇱', phoneCode: '+56', hasDelivery: true, deliveryCost: 40.00, deliveryDays: 15 },
  { code: 'CN', name: 'China', flagEmoji: '🇨🇳', phoneCode: '+86', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'CO', name: 'Colombia', flagEmoji: '🇨🇴', phoneCode: '+57', hasDelivery: true, deliveryCost: 40.00, deliveryDays: 15 },
  { code: 'KM', name: 'Comoros', flagEmoji: '🇰🇲', phoneCode: '+269', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'CG', name: 'Congo', flagEmoji: '🇨🇬', phoneCode: '+242', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'CR', name: 'Costa Rica', flagEmoji: '🇨🇷', phoneCode: '+506', hasDelivery: true, deliveryCost: 35.00, deliveryDays: 12 },
  { code: 'HR', name: 'Croatia', flagEmoji: '🇭🇷', phoneCode: '+385', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 5 },
  { code: 'CU', name: 'Cuba', flagEmoji: '🇨🇺', phoneCode: '+53', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'CY', name: 'Cyprus', flagEmoji: '🇨🇾', phoneCode: '+357', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 5 },
  { code: 'CZ', name: 'Czech Republic', flagEmoji: '🇨🇿', phoneCode: '+420', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 5 },
  { code: 'DK', name: 'Denmark', flagEmoji: '🇩🇰', phoneCode: '+45', hasDelivery: true, deliveryCost: 15.00, deliveryDays: 3 },
  { code: 'DJ', name: 'Djibouti', flagEmoji: '🇩🇯', phoneCode: '+253', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'DM', name: 'Dominica', flagEmoji: '🇩🇲', phoneCode: '+1767', hasDelivery: true, deliveryCost: 35.00, deliveryDays: 12 },
  { code: 'DO', name: 'Dominican Republic', flagEmoji: '🇩🇴', phoneCode: '+1809', hasDelivery: true, deliveryCost: 35.00, deliveryDays: 12 },
  { code: 'EC', name: 'Ecuador', flagEmoji: '🇪🇨', phoneCode: '+593', hasDelivery: true, deliveryCost: 40.00, deliveryDays: 15 },
  { code: 'EG', name: 'Egypt', flagEmoji: '🇪🇬', phoneCode: '+20', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'SV', name: 'El Salvador', flagEmoji: '🇸🇻', phoneCode: '+503', hasDelivery: true, deliveryCost: 35.00, deliveryDays: 12 },
  { code: 'GQ', name: 'Equatorial Guinea', flagEmoji: '🇬🇶', phoneCode: '+240', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'ER', name: 'Eritrea', flagEmoji: '🇪🇷', phoneCode: '+291', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'EE', name: 'Estonia', flagEmoji: '🇪🇪', phoneCode: '+372', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 5 },
  { code: 'ET', name: 'Ethiopia', flagEmoji: '🇪🇹', phoneCode: '+251', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'FJ', name: 'Fiji', flagEmoji: '🇫🇯', phoneCode: '+679', hasDelivery: true, deliveryCost: 40.00, deliveryDays: 15 },
  { code: 'FI', name: 'Finland', flagEmoji: '🇫🇮', phoneCode: '+358', hasDelivery: true, deliveryCost: 15.00, deliveryDays: 3 },
  { code: 'FR', name: 'France', flagEmoji: '🇫🇷', phoneCode: '+33', hasDelivery: true, deliveryCost: 15.00, deliveryDays: 3 },
  { code: 'GA', name: 'Gabon', flagEmoji: '🇬🇦', phoneCode: '+241', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'GM', name: 'Gambia', flagEmoji: '🇬🇲', phoneCode: '+220', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'GE', name: 'Georgia', flagEmoji: '🇬🇪', phoneCode: '+995', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'DE', name: 'Germany', flagEmoji: '🇩🇪', phoneCode: '+49', hasDelivery: true, deliveryCost: 15.00, deliveryDays: 3 },
  { code: 'GH', name: 'Ghana', flagEmoji: '🇬🇭', phoneCode: '+233', hasDelivery: true, deliveryCost: 30.00, deliveryDays: 10 },
  { code: 'GR', name: 'Greece', flagEmoji: '🇬🇷', phoneCode: '+30', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 5 },
  { code: 'GD', name: 'Grenada', flagEmoji: '🇬🇩', phoneCode: '+1473', hasDelivery: true, deliveryCost: 35.00, deliveryDays: 12 },
  { code: 'GT', name: 'Guatemala', flagEmoji: '🇬🇹', phoneCode: '+502', hasDelivery: true, deliveryCost: 35.00, deliveryDays: 12 },
  { code: 'GN', name: 'Guinea', flagEmoji: '🇬🇳', phoneCode: '+224', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'GW', name: 'Guinea-Bissau', flagEmoji: '🇬🇼', phoneCode: '+245', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'GY', name: 'Guyana', flagEmoji: '🇬🇾', phoneCode: '+592', hasDelivery: true, deliveryCost: 40.00, deliveryDays: 15 },
  { code: 'HT', name: 'Haiti', flagEmoji: '🇭🇹', phoneCode: '+509', hasDelivery: true, deliveryCost: 35.00, deliveryDays: 12 },
  { code: 'HN', name: 'Honduras', flagEmoji: '🇭🇳', phoneCode: '+504', hasDelivery: true, deliveryCost: 35.00, deliveryDays: 12 },
  { code: 'HK', name: 'Hong Kong', flagEmoji: '🇭🇰', phoneCode: '+852', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'HU', name: 'Hungary', flagEmoji: '🇭🇺', phoneCode: '+36', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 5 },
  { code: 'IS', name: 'Iceland', flagEmoji: '🇮🇸', phoneCode: '+354', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'IN', name: 'India', flagEmoji: '🇮🇳', phoneCode: '+91', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 6 },
  { code: 'ID', name: 'Indonesia', flagEmoji: '🇮🇩', phoneCode: '+62', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'IR', name: 'Iran', flagEmoji: '🇮🇷', phoneCode: '+98', hasDelivery: true, deliveryCost: 30.00, deliveryDays: 10 },
  { code: 'IQ', name: 'Iraq', flagEmoji: '🇮🇶', phoneCode: '+964', hasDelivery: true, deliveryCost: 30.00, deliveryDays: 10 },
  { code: 'IE', name: 'Ireland', flagEmoji: '🇮🇪', phoneCode: '+353', hasDelivery: true, deliveryCost: 15.00, deliveryDays: 3 },
  { code: 'IL', name: 'Israel', flagEmoji: '🇮🇱', phoneCode: '+972', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'IT', name: 'Italy', flagEmoji: '🇮🇹', phoneCode: '+39', hasDelivery: true, deliveryCost: 15.00, deliveryDays: 3 },
  { code: 'JM', name: 'Jamaica', flagEmoji: '🇯🇲', phoneCode: '+1876', hasDelivery: true, deliveryCost: 35.00, deliveryDays: 12 },
  { code: 'JP', name: 'Japan', flagEmoji: '🇯🇵', phoneCode: '+81', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'JO', name: 'Jordan', flagEmoji: '🇯🇴', phoneCode: '+962', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'KZ', name: 'Kazakhstan', flagEmoji: '🇰🇿', phoneCode: '+7', hasDelivery: true, deliveryCost: 30.00, deliveryDays: 10 },
  { code: 'KE', name: 'Kenya', flagEmoji: '🇰🇪', phoneCode: '+254', hasDelivery: true, deliveryCost: 30.00, deliveryDays: 10 },
  { code: 'KI', name: 'Kiribati', flagEmoji: '🇰🇮', phoneCode: '+686', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'KP', name: 'North Korea', flagEmoji: '🇰🇵', phoneCode: '+850', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'KR', name: 'South Korea', flagEmoji: '🇰🇷', phoneCode: '+82', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'KW', name: 'Kuwait', flagEmoji: '🇰🇼', phoneCode: '+965', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 7 },
  { code: 'KG', name: 'Kyrgyzstan', flagEmoji: '🇰🇬', phoneCode: '+996', hasDelivery: true, deliveryCost: 30.00, deliveryDays: 10 },
  { code: 'LA', name: 'Laos', flagEmoji: '🇱🇦', phoneCode: '+856', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'LV', name: 'Latvia', flagEmoji: '🇱🇻', phoneCode: '+371', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 5 },
  { code: 'LB', name: 'Lebanon', flagEmoji: '🇱🇧', phoneCode: '+961', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'LS', name: 'Lesotho', flagEmoji: '🇱🇸', phoneCode: '+266', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'LR', name: 'Liberia', flagEmoji: '🇱🇷', phoneCode: '+231', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'LY', name: 'Libya', flagEmoji: '🇱🇾', phoneCode: '+218', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'LI', name: 'Liechtenstein', flagEmoji: '🇱🇮', phoneCode: '+423', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 5 },
  { code: 'LT', name: 'Lithuania', flagEmoji: '🇱🇹', phoneCode: '+370', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 5 },
  { code: 'LU', name: 'Luxembourg', flagEmoji: '🇱🇺', phoneCode: '+352', hasDelivery: true, deliveryCost: 15.00, deliveryDays: 3 },
  { code: 'MO', name: 'Macau', flagEmoji: '🇲🇴', phoneCode: '+853', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'MK', name: 'North Macedonia', flagEmoji: '🇲🇰', phoneCode: '+389', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 5 },
  { code: 'MG', name: 'Madagascar', flagEmoji: '🇲🇬', phoneCode: '+261', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'MW', name: 'Malawi', flagEmoji: '🇲🇼', phoneCode: '+265', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'MY', name: 'Malaysia', flagEmoji: '🇲🇾', phoneCode: '+60', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'MV', name: 'Maldives', flagEmoji: '🇲🇻', phoneCode: '+960', hasDelivery: true, deliveryCost: 30.00, deliveryDays: 10 },
  { code: 'ML', name: 'Mali', flagEmoji: '🇲🇱', phoneCode: '+223', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'MT', name: 'Malta', flagEmoji: '🇲🇹', phoneCode: '+356', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 5 },
  { code: 'MH', name: 'Marshall Islands', flagEmoji: '🇲🇭', phoneCode: '+692', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'MR', name: 'Mauritania', flagEmoji: '🇲🇷', phoneCode: '+222', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'MU', name: 'Mauritius', flagEmoji: '🇲🇺', phoneCode: '+230', hasDelivery: true, deliveryCost: 30.00, deliveryDays: 10 },
  { code: 'MX', name: 'Mexico', flagEmoji: '🇲🇽', phoneCode: '+52', hasDelivery: true, deliveryCost: 35.00, deliveryDays: 12 },
  { code: 'FM', name: 'Micronesia', flagEmoji: '🇫🇲', phoneCode: '+691', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'MD', name: 'Moldova', flagEmoji: '🇲🇩', phoneCode: '+373', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'MC', name: 'Monaco', flagEmoji: '🇲🇨', phoneCode: '+377', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 5 },
  { code: 'MN', name: 'Mongolia', flagEmoji: '🇲🇳', phoneCode: '+976', hasDelivery: true, deliveryCost: 30.00, deliveryDays: 10 },
  { code: 'ME', name: 'Montenegro', flagEmoji: '🇲🇪', phoneCode: '+382', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 5 },
  { code: 'MA', name: 'Morocco', flagEmoji: '🇲🇦', phoneCode: '+212', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'MZ', name: 'Mozambique', flagEmoji: '🇲🇿', phoneCode: '+258', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'MM', name: 'Myanmar', flagEmoji: '🇲🇲', phoneCode: '+95', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'NA', name: 'Namibia', flagEmoji: '🇳🇦', phoneCode: '+264', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'NR', name: 'Nauru', flagEmoji: '🇳🇷', phoneCode: '+674', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'NP', name: 'Nepal', flagEmoji: '🇳🇵', phoneCode: '+977', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'NL', name: 'Netherlands', flagEmoji: '🇳🇱', phoneCode: '+31', hasDelivery: true, deliveryCost: 15.00, deliveryDays: 3 },
  { code: 'NZ', name: 'New Zealand', flagEmoji: '🇳🇿', phoneCode: '+64', hasDelivery: true, deliveryCost: 35.00, deliveryDays: 10 },
  { code: 'NI', name: 'Nicaragua', flagEmoji: '🇳🇮', phoneCode: '+505', hasDelivery: true, deliveryCost: 35.00, deliveryDays: 12 },
  { code: 'NE', name: 'Niger', flagEmoji: '🇳🇪', phoneCode: '+227', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'NG', name: 'Nigeria', flagEmoji: '🇳🇬', phoneCode: '+234', hasDelivery: true, deliveryCost: 30.00, deliveryDays: 10 },
  { code: 'NO', name: 'Norway', flagEmoji: '🇳🇴', phoneCode: '+47', hasDelivery: true, deliveryCost: 15.00, deliveryDays: 3 },
  { code: 'OM', name: 'Oman', flagEmoji: '🇴🇲', phoneCode: '+968', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 7 },
  { code: 'PK', name: 'Pakistan', flagEmoji: '🇵🇰', phoneCode: '+92', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 6 },
  { code: 'PW', name: 'Palau', flagEmoji: '🇵🇼', phoneCode: '+680', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'PA', name: 'Panama', flagEmoji: '🇵🇦', phoneCode: '+507', hasDelivery: true, deliveryCost: 35.00, deliveryDays: 12 },
  { code: 'PG', name: 'Papua New Guinea', flagEmoji: '🇵🇬', phoneCode: '+675', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'PY', name: 'Paraguay', flagEmoji: '🇵🇾', phoneCode: '+595', hasDelivery: true, deliveryCost: 40.00, deliveryDays: 15 },
  { code: 'PE', name: 'Peru', flagEmoji: '🇵🇪', phoneCode: '+51', hasDelivery: true, deliveryCost: 40.00, deliveryDays: 15 },
  { code: 'PH', name: 'Philippines', flagEmoji: '🇵🇭', phoneCode: '+63', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'PL', name: 'Poland', flagEmoji: '🇵🇱', phoneCode: '+48', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 5 },
  { code: 'PT', name: 'Portugal', flagEmoji: '🇵🇹', phoneCode: '+351', hasDelivery: true, deliveryCost: 15.00, deliveryDays: 3 },
  { code: 'QA', name: 'Qatar', flagEmoji: '🇶🇦', phoneCode: '+974', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 7 },
  { code: 'RO', name: 'Romania', flagEmoji: '🇷🇴', phoneCode: '+40', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 5 },
  { code: 'RU', name: 'Russia', flagEmoji: '🇷🇺', phoneCode: '+7', hasDelivery: true, deliveryCost: 30.00, deliveryDays: 10 },
  { code: 'RW', name: 'Rwanda', flagEmoji: '🇷🇼', phoneCode: '+250', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'KN', name: 'Saint Kitts and Nevis', flagEmoji: '🇰🇳', phoneCode: '+1869', hasDelivery: true, deliveryCost: 35.00, deliveryDays: 12 },
  { code: 'LC', name: 'Saint Lucia', flagEmoji: '🇱🇨', phoneCode: '+1758', hasDelivery: true, deliveryCost: 35.00, deliveryDays: 12 },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', flagEmoji: '🇻🇨', phoneCode: '+1784', hasDelivery: true, deliveryCost: 35.00, deliveryDays: 12 },
  { code: 'WS', name: 'Samoa', flagEmoji: '🇼🇸', phoneCode: '+685', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'SM', name: 'San Marino', flagEmoji: '🇸🇲', phoneCode: '+378', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 5 },
  { code: 'ST', name: 'Sao Tome and Principe', flagEmoji: '🇸🇹', phoneCode: '+239', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'SA', name: 'Saudi Arabia', flagEmoji: '🇸🇦', phoneCode: '+966', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 7 },
  { code: 'SN', name: 'Senegal', flagEmoji: '🇸🇳', phoneCode: '+221', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'RS', name: 'Serbia', flagEmoji: '🇷🇸', phoneCode: '+381', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 5 },
  { code: 'SC', name: 'Seychelles', flagEmoji: '🇸🇨', phoneCode: '+248', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'SL', name: 'Sierra Leone', flagEmoji: '🇸🇱', phoneCode: '+232', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'SG', name: 'Singapore', flagEmoji: '🇸🇬', phoneCode: '+65', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'SK', name: 'Slovakia', flagEmoji: '🇸🇰', phoneCode: '+421', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 5 },
  { code: 'SI', name: 'Slovenia', flagEmoji: '🇸🇮', phoneCode: '+386', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 5 },
  { code: 'SB', name: 'Solomon Islands', flagEmoji: '🇸🇧', phoneCode: '+677', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'SO', name: 'Somalia', flagEmoji: '🇸🇴', phoneCode: '+252', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'ZA', name: 'South Africa', flagEmoji: '🇿🇦', phoneCode: '+27', hasDelivery: true, deliveryCost: 30.00, deliveryDays: 10 },
  { code: 'ES', name: 'Spain', flagEmoji: '🇪🇸', phoneCode: '+34', hasDelivery: true, deliveryCost: 15.00, deliveryDays: 3 },
  { code: 'LK', name: 'Sri Lanka', flagEmoji: '🇱🇰', phoneCode: '+94', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'SD', name: 'Sudan', flagEmoji: '🇸🇩', phoneCode: '+249', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'SR', name: 'Suriname', flagEmoji: '🇸🇷', phoneCode: '+597', hasDelivery: true, deliveryCost: 40.00, deliveryDays: 15 },
  { code: 'SZ', name: 'Eswatini', flagEmoji: '🇸🇿', phoneCode: '+268', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'SE', name: 'Sweden', flagEmoji: '🇸🇪', phoneCode: '+46', hasDelivery: true, deliveryCost: 15.00, deliveryDays: 3 },
  { code: 'CH', name: 'Switzerland', flagEmoji: '🇨🇭', phoneCode: '+41', hasDelivery: true, deliveryCost: 15.00, deliveryDays: 3 },
  { code: 'SY', name: 'Syria', flagEmoji: '🇸🇾', phoneCode: '+963', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'TW', name: 'Taiwan', flagEmoji: '🇹🇼', phoneCode: '+886', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'TJ', name: 'Tajikistan', flagEmoji: '🇹🇯', phoneCode: '+992', hasDelivery: true, deliveryCost: 30.00, deliveryDays: 10 },
  { code: 'TZ', name: 'Tanzania', flagEmoji: '🇹🇿', phoneCode: '+255', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'TH', name: 'Thailand', flagEmoji: '🇹🇭', phoneCode: '+66', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'TL', name: 'Timor-Leste', flagEmoji: '🇹🇱', phoneCode: '+670', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'TG', name: 'Togo', flagEmoji: '🇹🇬', phoneCode: '+228', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'TO', name: 'Tonga', flagEmoji: '🇹🇴', phoneCode: '+676', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'TT', name: 'Trinidad and Tobago', flagEmoji: '🇹🇹', phoneCode: '+506', hasDelivery: true, deliveryCost: 35.00, deliveryDays: 12 },
  { code: 'TN', name: 'Tunisia', flagEmoji: '🇹🇳', phoneCode: '+216', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'TR', name: 'Turkey', flagEmoji: '🇹🇷', phoneCode: '+90', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'TM', name: 'Turkmenistan', flagEmoji: '🇹🇲', phoneCode: '+993', hasDelivery: true, deliveryCost: 30.00, deliveryDays: 10 },
  { code: 'TV', name: 'Tuvalu', flagEmoji: '🇹🇻', phoneCode: '+688', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'UG', name: 'Uganda', flagEmoji: '🇺🇬', phoneCode: '+256', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'UA', name: 'Ukraine', flagEmoji: '🇺🇦', phoneCode: '+380', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'AE', name: 'United Arab Emirates', flagEmoji: '🇦🇪', phoneCode: '+971', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 7 },
  { code: 'GB', name: 'United Kingdom', flagEmoji: '🇬🇧', phoneCode: '+44', hasDelivery: true, deliveryCost: 15.00, deliveryDays: 3 },
  { code: 'US', name: 'United States', flagEmoji: '🇺🇸', phoneCode: '+1', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 5 },
  { code: 'UY', name: 'Uruguay', flagEmoji: '🇺🇾', phoneCode: '+598', hasDelivery: true, deliveryCost: 40.00, deliveryDays: 15 },
  { code: 'UZ', name: 'Uzbekistan', flagEmoji: '🇺🇿', phoneCode: '+998', hasDelivery: true, deliveryCost: 30.00, deliveryDays: 10 },
  { code: 'VU', name: 'Vanuatu', flagEmoji: '🇻🇺', phoneCode: '+678', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'VA', name: 'Vatican City', flagEmoji: '🇻🇦', phoneCode: '+379', hasDelivery: true, deliveryCost: 20.00, deliveryDays: 5 },
  { code: 'VE', name: 'Venezuela', flagEmoji: '🇻🇪', phoneCode: '+58', hasDelivery: true, deliveryCost: 40.00, deliveryDays: 15 },
  { code: 'VN', name: 'Vietnam', flagEmoji: '🇻🇳', phoneCode: '+84', hasDelivery: true, deliveryCost: 25.00, deliveryDays: 8 },
  { code: 'YE', name: 'Yemen', flagEmoji: '🇾🇪', phoneCode: '+967', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'ZM', name: 'Zambia', flagEmoji: '🇿🇲', phoneCode: '+260', hasDelivery: false, deliveryCost: null, deliveryDays: null },
  { code: 'ZW', name: 'Zimbabwe', flagEmoji: '🇿🇼', phoneCode: '+263', hasDelivery: false, deliveryCost: null, deliveryDays: null }
];

async function main() {
  console.log('🌍 Starting countries database seeding...');

  // Clear existing country data
  await prisma.countryConfig.deleteMany();

  // Create countries
  const createdCountries = await Promise.all(
    countries.map((country, index) =>
      prisma.countryConfig.create({
        data: {
          ...country,
          isActive: true,
          isDefault: country.code === 'US', // Set US as default
          sortOrder: index + 1
        }
      })
    )
  );

  console.log(`✅ Created ${createdCountries.length} countries`);
  
  // Log delivery statistics
  const deliveryCountries = createdCountries.filter(c => c.hasDelivery);
  const nonDeliveryCountries = createdCountries.filter(c => !c.hasDelivery);
  
  console.log(`🚚 Countries with delivery: ${deliveryCountries.length}`);
  console.log(`❌ Countries without delivery: ${nonDeliveryCountries.length}`);
  console.log(`🌍 Total countries: ${createdCountries.length}`);
}

main()
  .catch((e) => {
    console.error('❌ Error seeding countries:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
