import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌍 Seeding tax and shipping rates...');

  // Tax Rates - Realistic values for common countries
  const taxRates = [
    // United States - State Sales Tax
    { countryCode: 'US', stateCode: 'CA', taxRate: 7.25, taxName: 'California State Sales Tax' },
    { countryCode: 'US', stateCode: 'TX', taxRate: 6.25, taxName: 'Texas State Sales Tax' },
    { countryCode: 'US', stateCode: 'NY', taxRate: 8.875, taxName: 'New York State Sales Tax' },
    { countryCode: 'US', stateCode: 'FL', taxRate: 6.00, taxName: 'Florida State Sales Tax' },
    { countryCode: 'US', stateCode: 'IL', taxRate: 6.25, taxName: 'Illinois State Sales Tax' },
    { countryCode: 'US', stateCode: 'PA', taxRate: 6.00, taxName: 'Pennsylvania State Sales Tax' },
    { countryCode: 'US', stateCode: 'OH', taxRate: 5.75, taxName: 'Ohio State Sales Tax' },
    { countryCode: 'US', stateCode: 'GA', taxRate: 4.00, taxName: 'Georgia State Sales Tax' },
    { countryCode: 'US', stateCode: 'NC', taxRate: 4.75, taxName: 'North Carolina State Sales Tax' },
    { countryCode: 'US', stateCode: 'MI', taxRate: 6.00, taxName: 'Michigan State Sales Tax' },
    { countryCode: 'US', stateCode: 'WA', taxRate: 6.50, taxName: 'Washington State Sales Tax' },
    { countryCode: 'US', stateCode: 'OR', taxRate: 0.00, taxName: 'Oregon (No Sales Tax)' },
    { countryCode: 'US', stateCode: 'DE', taxRate: 0.00, taxName: 'Delaware (No Sales Tax)' },
    { countryCode: 'US', stateCode: 'MT', taxRate: 0.00, taxName: 'Montana (No Sales Tax)' },
    { countryCode: 'US', stateCode: 'NH', taxRate: 0.00, taxName: 'New Hampshire (No Sales Tax)' },
    { countryCode: 'US', stateCode: 'AK', taxRate: 0.00, taxName: 'Alaska (No Sales Tax)' },

    // Canada - GST/HST/PST
    { countryCode: 'CA', stateCode: 'ON', taxRate: 13.00, taxName: 'Ontario HST' },
    { countryCode: 'CA', stateCode: 'BC', taxRate: 12.00, taxName: 'British Columbia HST' },
    { countryCode: 'CA', stateCode: 'AB', taxRate: 5.00, taxName: 'Alberta GST' },
    { countryCode: 'CA', stateCode: 'QC', taxRate: 14.975, taxName: 'Quebec GST + QST' },
    { countryCode: 'CA', stateCode: 'NS', taxRate: 15.00, taxName: 'Nova Scotia HST' },
    { countryCode: 'CA', stateCode: 'NB', taxRate: 15.00, taxName: 'New Brunswick HST' },
    { countryCode: 'CA', stateCode: 'NL', taxRate: 15.00, taxName: 'Newfoundland and Labrador HST' },
    { countryCode: 'CA', stateCode: 'PE', taxRate: 15.00, taxName: 'Prince Edward Island HST' },
    { countryCode: 'CA', stateCode: 'MB', taxRate: 12.00, taxName: 'Manitoba GST + PST' },
    { countryCode: 'CA', stateCode: 'SK', taxRate: 11.00, taxName: 'Saskatchewan GST + PST' },

    // United Kingdom
    { countryCode: 'GB', stateCode: null, taxRate: 20.00, taxName: 'UK VAT' },

    // European Union - VAT Rates
    { countryCode: 'DE', stateCode: null, taxRate: 19.00, taxName: 'German VAT' },
    { countryCode: 'FR', stateCode: null, taxRate: 20.00, taxName: 'French VAT' },
    { countryCode: 'IT', stateCode: null, taxRate: 22.00, taxName: 'Italian VAT' },
    { countryCode: 'ES', stateCode: null, taxRate: 21.00, taxName: 'Spanish VAT' },
    { countryCode: 'NL', stateCode: null, taxRate: 21.00, taxName: 'Dutch VAT' },
    { countryCode: 'BE', stateCode: null, taxRate: 21.00, taxName: 'Belgian VAT' },
    { countryCode: 'AT', stateCode: null, taxRate: 20.00, taxName: 'Austrian VAT' },
    { countryCode: 'SE', stateCode: null, taxRate: 25.00, taxName: 'Swedish VAT' },
    { countryCode: 'DK', stateCode: null, taxRate: 25.00, taxName: 'Danish VAT' },
    { countryCode: 'FI', stateCode: null, taxRate: 24.00, taxName: 'Finnish VAT' },
    { countryCode: 'PL', stateCode: null, taxRate: 23.00, taxName: 'Polish VAT' },
    { countryCode: 'CZ', stateCode: null, taxRate: 21.00, taxName: 'Czech VAT' },
    { countryCode: 'HU', stateCode: null, taxRate: 27.00, taxName: 'Hungarian VAT' },
    { countryCode: 'RO', stateCode: null, taxRate: 19.00, taxName: 'Romanian VAT' },
    { countryCode: 'BG', stateCode: null, taxRate: 20.00, taxName: 'Bulgarian VAT' },
    { countryCode: 'HR', stateCode: null, taxRate: 25.00, taxName: 'Croatian VAT' },
    { countryCode: 'SI', stateCode: null, taxRate: 22.00, taxName: 'Slovenian VAT' },
    { countryCode: 'SK', stateCode: null, taxRate: 20.00, taxName: 'Slovak VAT' },
    { countryCode: 'EE', stateCode: null, taxRate: 20.00, taxName: 'Estonian VAT' },
    { countryCode: 'LV', stateCode: null, taxRate: 21.00, taxName: 'Latvian VAT' },
    { countryCode: 'LT', stateCode: null, taxRate: 21.00, taxName: 'Lithuanian VAT' },
    { countryCode: 'IE', stateCode: null, taxRate: 23.00, taxName: 'Irish VAT' },
    { countryCode: 'PT', stateCode: null, taxRate: 23.00, taxName: 'Portuguese VAT' },
    { countryCode: 'GR', stateCode: null, taxRate: 24.00, taxName: 'Greek VAT' },
    { countryCode: 'CY', stateCode: null, taxRate: 19.00, taxName: 'Cypriot VAT' },
    { countryCode: 'LU', stateCode: null, taxRate: 17.00, taxName: 'Luxembourg VAT' },
    { countryCode: 'MT', stateCode: null, taxRate: 18.00, taxName: 'Maltese VAT' },

    // Asia Pacific
    { countryCode: 'JP', stateCode: null, taxRate: 10.00, taxName: 'Japanese Consumption Tax' },
    { countryCode: 'KR', stateCode: null, taxRate: 10.00, taxName: 'Korean VAT' },
    { countryCode: 'AU', stateCode: null, taxRate: 10.00, taxName: 'Australian GST' },
    { countryCode: 'NZ', stateCode: null, taxRate: 15.00, taxName: 'New Zealand GST' },
    { countryCode: 'SG', stateCode: null, taxRate: 8.00, taxName: 'Singapore GST' },
    { countryCode: 'MY', stateCode: null, taxRate: 10.00, taxName: 'Malaysian SST' },
    { countryCode: 'TH', stateCode: null, taxRate: 7.00, taxName: 'Thai VAT' },
    { countryCode: 'VN', stateCode: null, taxRate: 10.00, taxName: 'Vietnamese VAT' },
    { countryCode: 'ID', stateCode: null, taxRate: 11.00, taxName: 'Indonesian VAT' },
    { countryCode: 'PH', stateCode: null, taxRate: 12.00, taxName: 'Philippine VAT' },
    { countryCode: 'IN', stateCode: null, taxRate: 18.00, taxName: 'Indian GST' },
    { countryCode: 'PK', stateCode: null, taxRate: 17.00, taxName: 'Pakistani GST' },
    { countryCode: 'BD', stateCode: null, taxRate: 15.00, taxName: 'Bangladeshi VAT' },
    { countryCode: 'LK', stateCode: null, taxRate: 12.00, taxName: 'Sri Lankan VAT' },
    { countryCode: 'NP', stateCode: null, taxRate: 13.00, taxName: 'Nepalese VAT' },
    { countryCode: 'MM', stateCode: null, taxRate: 5.00, taxName: 'Myanmar Commercial Tax' },
    { countryCode: 'KH', stateCode: null, taxRate: 10.00, taxName: 'Cambodian VAT' },
    { countryCode: 'LA', stateCode: null, taxRate: 10.00, taxName: 'Laotian VAT' },
    { countryCode: 'MN', stateCode: null, taxRate: 10.00, taxName: 'Mongolian VAT' },
    { countryCode: 'KZ', stateCode: null, taxRate: 12.00, taxName: 'Kazakhstan VAT' },
    { countryCode: 'UZ', stateCode: null, taxRate: 15.00, taxName: 'Uzbekistan VAT' },
    { countryCode: 'TJ', stateCode: null, taxRate: 18.00, taxName: 'Tajikistan VAT' },
    { countryCode: 'TM', stateCode: null, taxRate: 20.00, taxName: 'Turkmenistan VAT' },
    { countryCode: 'AZ', stateCode: null, taxRate: 18.00, taxName: 'Azerbaijan VAT' },
    { countryCode: 'GE', stateCode: null, taxRate: 18.00, taxName: 'Georgian VAT' },
    { countryCode: 'AM', stateCode: null, taxRate: 20.00, taxName: 'Armenian VAT' },
    { countryCode: 'BY', stateCode: null, taxRate: 20.00, taxName: 'Belarus VAT' },
    { countryCode: 'MD', stateCode: null, taxRate: 20.00, taxName: 'Moldovan VAT' },
    { countryCode: 'UA', stateCode: null, taxRate: 20.00, taxName: 'Ukrainian VAT' },
    { countryCode: 'RO', stateCode: null, taxRate: 19.00, taxName: 'Romanian VAT' },

    // Middle East
    { countryCode: 'AE', stateCode: null, taxRate: 5.00, taxName: 'UAE VAT' },
    { countryCode: 'SA', stateCode: null, taxRate: 15.00, taxName: 'Saudi VAT' },
    { countryCode: 'QA', stateCode: null, taxRate: 0.00, taxName: 'Qatar (No VAT)' },
    { countryCode: 'KW', stateCode: null, taxRate: 0.00, taxName: 'Kuwait (No VAT)' },
    { countryCode: 'BH', stateCode: null, taxRate: 5.00, taxName: 'Bahrain VAT' },
    { countryCode: 'OM', stateCode: null, taxRate: 5.00, taxName: 'Oman VAT' },
    { countryCode: 'JO', stateCode: null, taxRate: 16.00, taxName: 'Jordan VAT' },
    { countryCode: 'LB', stateCode: null, taxRate: 11.00, taxName: 'Lebanese VAT' },
    { countryCode: 'IL', stateCode: null, taxRate: 17.00, taxName: 'Israeli VAT' },
    { countryCode: 'IR', stateCode: null, taxRate: 9.00, taxName: 'Iranian VAT' },
    { countryCode: 'AF', stateCode: null, taxRate: 0.00, taxName: 'Afghanistan (No VAT)' },

    // Africa
    { countryCode: 'ZA', stateCode: null, taxRate: 15.00, taxName: 'South African VAT' },
    { countryCode: 'EG', stateCode: null, taxRate: 14.00, taxName: 'Egyptian VAT' },
    { countryCode: 'NG', stateCode: null, taxRate: 7.50, taxName: 'Nigerian VAT' },
    { countryCode: 'KE', stateCode: null, taxRate: 16.00, taxName: 'Kenyan VAT' },
    { countryCode: 'GH', stateCode: null, taxRate: 12.50, taxName: 'Ghanaian VAT' },
    { countryCode: 'MA', stateCode: null, taxRate: 20.00, taxName: 'Moroccan VAT' },
    { countryCode: 'TN', stateCode: null, taxRate: 19.00, taxName: 'Tunisian VAT' },
    { countryCode: 'DZ', stateCode: null, taxRate: 19.00, taxName: 'Algerian VAT' },
    { countryCode: 'LY', stateCode: null, taxRate: 0.00, taxName: 'Libya (No VAT)' },
    { countryCode: 'SD', stateCode: null, taxRate: 17.00, taxName: 'Sudanese VAT' },
    { countryCode: 'ET', stateCode: null, taxRate: 15.00, taxName: 'Ethiopian VAT' },
    { countryCode: 'TZ', stateCode: null, taxRate: 18.00, taxName: 'Tanzanian VAT' },
    { countryCode: 'UG', stateCode: null, taxRate: 18.00, taxName: 'Ugandan VAT' },
    { countryCode: 'ZM', stateCode: null, taxRate: 16.00, taxName: 'Zambian VAT' },
    { countryCode: 'ZW', stateCode: null, taxRate: 14.50, taxName: 'Zimbabwean VAT' },
    { countryCode: 'BW', stateCode: null, taxRate: 12.00, taxName: 'Botswana VAT' },
    { countryCode: 'NA', stateCode: null, taxRate: 15.00, taxName: 'Namibian VAT' },
    { countryCode: 'SZ', stateCode: null, taxRate: 15.00, taxName: 'Eswatini VAT' },
    { countryCode: 'LS', stateCode: null, taxRate: 15.00, taxName: 'Lesotho VAT' },
    { countryCode: 'MW', stateCode: null, taxRate: 16.50, taxName: 'Malawian VAT' },
    { countryCode: 'MZ', stateCode: null, taxRate: 17.00, taxName: 'Mozambican VAT' },
    { countryCode: 'AO', stateCode: null, taxRate: 14.00, taxName: 'Angolan VAT' },
    { countryCode: 'CD', stateCode: null, taxRate: 16.00, taxName: 'DR Congo VAT' },
    { countryCode: 'CG', stateCode: null, taxRate: 18.90, taxName: 'Congo VAT' },
    { countryCode: 'GA', stateCode: null, taxRate: 18.00, taxName: 'Gabonese VAT' },
    { countryCode: 'CM', stateCode: null, taxRate: 19.25, taxName: 'Cameroonian VAT' },
    { countryCode: 'TD', stateCode: null, taxRate: 18.00, taxName: 'Chadian VAT' },
    { countryCode: 'NE', stateCode: null, taxRate: 19.00, taxName: 'Niger VAT' },
    { countryCode: 'ML', stateCode: null, taxRate: 18.00, taxName: 'Malian VAT' },
    { countryCode: 'BF', stateCode: null, taxRate: 18.00, taxName: 'Burkina Faso VAT' },
    { countryCode: 'CI', stateCode: null, taxRate: 18.00, taxName: 'Ivorian VAT' },
    { countryCode: 'SN', stateCode: null, taxRate: 18.00, taxName: 'Senegalese VAT' },
    { countryCode: 'GN', stateCode: null, taxRate: 18.00, taxName: 'Guinean VAT' },
    { countryCode: 'SL', stateCode: null, taxRate: 15.00, taxName: 'Sierra Leone VAT' },
    { countryCode: 'LR', stateCode: null, taxRate: 10.00, taxName: 'Liberian VAT' },
    { countryCode: 'GW', stateCode: null, taxRate: 15.00, taxName: 'Guinea-Bissau VAT' },
    { countryCode: 'CV', stateCode: null, taxRate: 15.00, taxName: 'Cape Verdean VAT' },
    { countryCode: 'GM', stateCode: null, taxRate: 15.00, taxName: 'Gambian VAT' },
    { countryCode: 'GN', stateCode: null, taxRate: 18.00, taxName: 'Guinean VAT' },
    { countryCode: 'SL', stateCode: null, taxRate: 15.00, taxName: 'Sierra Leone VAT' },
    { countryCode: 'LR', stateCode: null, taxRate: 10.00, taxName: 'Liberian VAT' },
    { countryCode: 'GW', stateCode: null, taxRate: 15.00, taxName: 'Guinea-Bissau VAT' },
    { countryCode: 'CV', stateCode: null, taxRate: 15.00, taxName: 'Cape Verdean VAT' },
    { countryCode: 'GM', stateCode: null, taxRate: 15.00, taxName: 'Gambian VAT' },

    // Americas
    { countryCode: 'MX', stateCode: null, taxRate: 16.00, taxName: 'Mexican VAT' },
    { countryCode: 'BR', stateCode: null, taxRate: 17.00, taxName: 'Brazilian ICMS' },
    { countryCode: 'AR', stateCode: null, taxRate: 21.00, taxName: 'Argentine VAT' },
    { countryCode: 'CL', stateCode: null, taxRate: 19.00, taxName: 'Chilean VAT' },
    { countryCode: 'CO', stateCode: null, taxRate: 19.00, taxName: 'Colombian VAT' },
    { countryCode: 'PE', stateCode: null, taxRate: 18.00, taxName: 'Peruvian VAT' },
    { countryCode: 'UY', stateCode: null, taxRate: 22.00, taxName: 'Uruguayan VAT' },
    { countryCode: 'PY', stateCode: null, taxRate: 10.00, taxName: 'Paraguayan VAT' },
    { countryCode: 'GY', stateCode: null, taxRate: 14.00, taxName: 'Guyanese VAT' },
    { countryCode: 'SR', stateCode: null, taxRate: 10.00, taxName: 'Surinamese VAT' },
    { countryCode: 'FJ', stateCode: null, taxRate: 9.00, taxName: 'Fijian VAT' },
    { countryCode: 'PG', stateCode: null, taxRate: 10.00, taxName: 'Papua New Guinean VAT' },
    { countryCode: 'WS', stateCode: null, taxRate: 15.00, taxName: 'Samoan VAT' },
    { countryCode: 'TO', stateCode: null, taxRate: 15.00, taxName: 'Tongan VAT' },
    { countryCode: 'VU', stateCode: null, taxRate: 12.50, taxName: 'Vanuatu VAT' },
    { countryCode: 'SB', stateCode: null, taxRate: 10.00, taxName: 'Solomon Islands VAT' },
    { countryCode: 'KI', stateCode: null, taxRate: 12.50, taxName: 'Kiribati VAT' },
    { countryCode: 'TV', stateCode: null, taxRate: 0.00, taxName: 'Tuvalu (No VAT)' },
  ];

  // Shipping Rates - Realistic values for common countries
  const shippingRates = [
    // United States - Domestic shipping
    { countryCode: 'US', stateCode: 'CA', shippingCost: 5.99, deliveryDays: 3 },
    { countryCode: 'US', stateCode: 'TX', shippingCost: 6.99, deliveryDays: 4 },
    { countryCode: 'US', stateCode: 'NY', shippingCost: 5.99, deliveryDays: 3 },
    { countryCode: 'US', stateCode: 'FL', shippingCost: 7.99, deliveryDays: 4 },
    { countryCode: 'US', stateCode: 'IL', shippingCost: 6.99, deliveryDays: 4 },
    { countryCode: 'US', stateCode: 'PA', shippingCost: 6.99, deliveryDays: 4 },
    { countryCode: 'US', stateCode: 'OH', shippingCost: 6.99, deliveryDays: 4 },
    { countryCode: 'US', stateCode: 'GA', shippingCost: 7.99, deliveryDays: 4 },
    { countryCode: 'US', stateCode: 'NC', shippingCost: 7.99, deliveryDays: 4 },
    { countryCode: 'US', stateCode: 'MI', shippingCost: 6.99, deliveryDays: 4 },
    { countryCode: 'US', stateCode: 'WA', shippingCost: 8.99, deliveryDays: 5 },
    { countryCode: 'US', stateCode: 'OR', shippingCost: 8.99, deliveryDays: 5 },
    { countryCode: 'US', stateCode: 'DE', shippingCost: 5.99, deliveryDays: 3 },
    { countryCode: 'US', stateCode: 'MT', shippingCost: 9.99, deliveryDays: 6 },
    { countryCode: 'US', stateCode: 'NH', shippingCost: 6.99, deliveryDays: 4 },
    { countryCode: 'US', stateCode: 'AK', shippingCost: 14.99, deliveryDays: 8 },

    // Canada - Domestic shipping
    { countryCode: 'CA', stateCode: 'ON', shippingCost: 8.99, deliveryDays: 4 },
    { countryCode: 'CA', stateCode: 'BC', shippingCost: 9.99, deliveryDays: 5 },
    { countryCode: 'CA', stateCode: 'AB', shippingCost: 8.99, deliveryDays: 4 },
    { countryCode: 'CA', stateCode: 'QC', shippingCost: 8.99, deliveryDays: 4 },
    { countryCode: 'CA', stateCode: 'NS', shippingCost: 9.99, deliveryDays: 5 },
    { countryCode: 'CA', stateCode: 'NB', shippingCost: 9.99, deliveryDays: 5 },
    { countryCode: 'CA', stateCode: 'NL', shippingCost: 10.99, deliveryDays: 6 },
    { countryCode: 'CA', stateCode: 'PE', shippingCost: 9.99, deliveryDays: 5 },
    { countryCode: 'CA', stateCode: 'MB', shippingCost: 8.99, deliveryDays: 4 },
    { countryCode: 'CA', stateCode: 'SK', shippingCost: 8.99, deliveryDays: 4 },

    // International shipping - Major countries
    { countryCode: 'GB', stateCode: null, shippingCost: 12.99, deliveryDays: 7 },
    { countryCode: 'DE', stateCode: null, shippingCost: 13.99, deliveryDays: 8 },
    { countryCode: 'FR', stateCode: null, shippingCost: 13.99, deliveryDays: 8 },
    { countryCode: 'IT', stateCode: null, shippingCost: 14.99, deliveryDays: 8 },
    { countryCode: 'ES', stateCode: null, shippingCost: 14.99, deliveryDays: 8 },
    { countryCode: 'NL', stateCode: null, shippingCost: 13.99, deliveryDays: 8 },
    { countryCode: 'BE', stateCode: null, shippingCost: 13.99, deliveryDays: 8 },
    { countryCode: 'AT', stateCode: null, shippingCost: 13.99, deliveryDays: 8 },
    { countryCode: 'SE', stateCode: null, shippingCost: 14.99, deliveryDays: 8 },
    { countryCode: 'DK', stateCode: null, shippingCost: 14.99, deliveryDays: 8 },
    { countryCode: 'FI', stateCode: null, shippingCost: 14.99, deliveryDays: 8 },
    { countryCode: 'PL', stateCode: null, shippingCost: 14.99, deliveryDays: 8 },
    { countryCode: 'CZ', stateCode: null, shippingCost: 13.99, deliveryDays: 8 },
    { countryCode: 'HU', stateCode: null, shippingCost: 14.99, deliveryDays: 8 },
    { countryCode: 'RO', stateCode: null, shippingCost: 13.99, deliveryDays: 8 },
    { countryCode: 'BG', stateCode: null, shippingCost: 13.99, deliveryDays: 8 },
    { countryCode: 'HR', stateCode: null, shippingCost: 14.99, deliveryDays: 8 },
    { countryCode: 'SI', stateCode: null, shippingCost: 13.99, deliveryDays: 8 },
    { countryCode: 'SK', stateCode: null, shippingCost: 13.99, deliveryDays: 8 },
    { countryCode: 'EE', stateCode: null, shippingCost: 13.99, deliveryDays: 8 },
    { countryCode: 'LV', stateCode: null, shippingCost: 13.99, deliveryDays: 8 },
    { countryCode: 'LT', stateCode: null, shippingCost: 13.99, deliveryDays: 8 },
    { countryCode: 'IE', stateCode: null, shippingCost: 13.99, deliveryDays: 8 },
    { countryCode: 'PT', stateCode: null, shippingCost: 14.99, deliveryDays: 8 },
    { countryCode: 'GR', stateCode: null, shippingCost: 14.99, deliveryDays: 8 },
    { countryCode: 'CY', stateCode: null, shippingCost: 13.99, deliveryDays: 8 },
    { countryCode: 'LU', stateCode: null, shippingCost: 13.99, deliveryDays: 8 },
    { countryCode: 'MT', stateCode: null, shippingCost: 13.99, deliveryDays: 8 },

    // Asia Pacific
    { countryCode: 'JP', stateCode: null, shippingCost: 16.99, deliveryDays: 10 },
    { countryCode: 'KR', stateCode: null, shippingCost: 15.99, deliveryDays: 9 },
    { countryCode: 'AU', stateCode: null, shippingCost: 18.99, deliveryDays: 12 },
    { countryCode: 'NZ', stateCode: null, shippingCost: 19.99, deliveryDays: 12 },
    { countryCode: 'SG', stateCode: null, shippingCost: 14.99, deliveryDays: 8 },
    { countryCode: 'MY', stateCode: null, shippingCost: 15.99, deliveryDays: 9 },
    { countryCode: 'TH', stateCode: null, shippingCost: 15.99, deliveryDays: 9 },
    { countryCode: 'VN', stateCode: null, shippingCost: 15.99, deliveryDays: 9 },
    { countryCode: 'ID', stateCode: null, shippingCost: 16.99, deliveryDays: 10 },
    { countryCode: 'PH', stateCode: null, shippingCost: 16.99, deliveryDays: 10 },
    { countryCode: 'IN', stateCode: null, shippingCost: 17.99, deliveryDays: 11 },
    { countryCode: 'PK', stateCode: null, shippingCost: 18.99, deliveryDays: 12 },
    { countryCode: 'BD', stateCode: null, shippingCost: 17.99, deliveryDays: 11 },
    { countryCode: 'LK', stateCode: null, shippingCost: 17.99, deliveryDays: 11 },
    { countryCode: 'NP', stateCode: null, shippingCost: 18.99, deliveryDays: 12 },
    { countryCode: 'MM', stateCode: null, shippingCost: 16.99, deliveryDays: 10 },
    { countryCode: 'KH', stateCode: null, shippingCost: 15.99, deliveryDays: 9 },
    { countryCode: 'LA', stateCode: null, shippingCost: 15.99, deliveryDays: 9 },
    { countryCode: 'MN', stateCode: null, shippingCost: 16.99, deliveryDays: 10 },
    { countryCode: 'KZ', stateCode: null, shippingCost: 17.99, deliveryDays: 11 },
    { countryCode: 'UZ', stateCode: null, shippingCost: 17.99, deliveryDays: 11 },
    { countryCode: 'TJ', stateCode: null, shippingCost: 18.99, deliveryDays: 12 },
    { countryCode: 'TM', stateCode: null, shippingCost: 18.99, deliveryDays: 12 },
    { countryCode: 'AZ', stateCode: null, shippingCost: 17.99, deliveryDays: 11 },
    { countryCode: 'GE', stateCode: null, shippingCost: 17.99, deliveryDays: 11 },
    { countryCode: 'AM', stateCode: null, shippingCost: 17.99, deliveryDays: 11 },
    { countryCode: 'BY', stateCode: null, shippingCost: 17.99, deliveryDays: 11 },
    { countryCode: 'MD', stateCode: null, shippingCost: 17.99, deliveryDays: 11 },
    { countryCode: 'UA', stateCode: null, shippingCost: 17.99, deliveryDays: 11 },

    // Middle East
    { countryCode: 'AE', stateCode: null, shippingCost: 16.99, deliveryDays: 10 },
    { countryCode: 'SA', stateCode: null, shippingCost: 17.99, deliveryDays: 11 },
    { countryCode: 'QA', stateCode: null, shippingCost: 16.99, deliveryDays: 10 },
    { countryCode: 'KW', stateCode: null, shippingCost: 16.99, deliveryDays: 10 },
    { countryCode: 'BH', stateCode: null, shippingCost: 16.99, deliveryDays: 10 },
    { countryCode: 'OM', stateCode: null, shippingCost: 16.99, deliveryDays: 10 },
    { countryCode: 'JO', stateCode: null, shippingCost: 17.99, deliveryDays: 11 },
    { countryCode: 'LB', stateCode: null, shippingCost: 17.99, deliveryDays: 11 },
    { countryCode: 'IL', stateCode: null, shippingCost: 17.99, deliveryDays: 11 },
    { countryCode: 'IR', stateCode: null, shippingCost: 18.99, deliveryDays: 12 },
    { countryCode: 'AF', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },

    // Africa
    { countryCode: 'ZA', stateCode: null, shippingCost: 19.99, deliveryDays: 12 },
    { countryCode: 'EG', stateCode: null, shippingCost: 18.99, deliveryDays: 12 },
    { countryCode: 'NG', stateCode: null, shippingCost: 19.99, deliveryDays: 12 },
    { countryCode: 'KE', stateCode: null, shippingCost: 19.99, deliveryDays: 12 },
    { countryCode: 'GH', stateCode: null, shippingCost: 19.99, deliveryDays: 12 },
    { countryCode: 'MA', stateCode: null, shippingCost: 18.99, deliveryDays: 12 },
    { countryCode: 'TN', stateCode: null, shippingCost: 18.99, deliveryDays: 12 },
    { countryCode: 'DZ', stateCode: null, shippingCost: 18.99, deliveryDays: 12 },
    { countryCode: 'LY', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'SD', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'ET', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'TZ', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'UG', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'ZM', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'ZW', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'BW', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'NA', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'SZ', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'LS', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'MW', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'MZ', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'AO', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'CD', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'CG', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'GA', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'CM', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'TD', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'NE', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'ML', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'BF', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'CI', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'SN', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'GN', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'SL', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'LR', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'GW', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'CV', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },
    { countryCode: 'GM', stateCode: null, shippingCost: 19.99, deliveryDays: 13 },

    // Americas
    { countryCode: 'MX', stateCode: null, shippingCost: 12.99, deliveryDays: 7 },
    { countryCode: 'BR', stateCode: null, shippingCost: 13.99, deliveryDays: 8 },
    { countryCode: 'AR', stateCode: null, shippingCost: 14.99, deliveryDays: 8 },
    { countryCode: 'CL', stateCode: null, shippingCost: 13.99, deliveryDays: 8 },
    { countryCode: 'CO', stateCode: null, shippingCost: 13.99, deliveryDays: 8 },
    { countryCode: 'PE', stateCode: null, shippingCost: 13.99, deliveryDays: 8 },
    { countryCode: 'UY', stateCode: null, shippingCost: 14.99, deliveryDays: 8 },
    { countryCode: 'PY', stateCode: null, shippingCost: 12.99, deliveryDays: 7 },
    { countryCode: 'GY', stateCode: null, shippingCost: 13.99, deliveryDays: 8 },
    { countryCode: 'SR', stateCode: null, shippingCost: 12.99, deliveryDays: 7 },
    { countryCode: 'FJ', stateCode: null, shippingCost: 15.99, deliveryDays: 9 },
    { countryCode: 'PG', stateCode: null, shippingCost: 16.99, deliveryDays: 10 },
    { countryCode: 'WS', stateCode: null, shippingCost: 16.99, deliveryDays: 10 },
    { countryCode: 'TO', stateCode: null, shippingCost: 16.99, deliveryDays: 10 },
    { countryCode: 'VU', stateCode: null, shippingCost: 16.99, deliveryDays: 10 },
    { countryCode: 'SB', stateCode: null, shippingCost: 15.99, deliveryDays: 9 },
    { countryCode: 'KI', stateCode: null, shippingCost: 16.99, deliveryDays: 10 },
    { countryCode: 'TV', stateCode: null, shippingCost: 17.99, deliveryDays: 11 },
  ];

  // Insert tax rates
  console.log('📊 Inserting tax rates...');
  for (const taxRate of taxRates) {
    await prisma.taxRate.create({
      data: {
        countryCode: taxRate.countryCode,
        stateCode: taxRate.stateCode,
        taxRate: taxRate.taxRate,
        taxName: taxRate.taxName,
        isActive: true
      }
    });
  }

  // Insert shipping rates
  console.log('🚚 Inserting shipping rates...');
  for (const shippingRate of shippingRates) {
    await prisma.shippingRate.create({
      data: {
        countryCode: shippingRate.countryCode,
        stateCode: shippingRate.stateCode,
        shippingCost: shippingRate.shippingCost,
        deliveryDays: shippingRate.deliveryDays,
        isActive: true
      }
    });
  }

  console.log('✅ Tax and shipping rates seeded successfully!');
  console.log(`📊 Tax rates: ${taxRates.length}`);
  console.log(`🚚 Shipping rates: ${shippingRates.length}`);
}

main()
  .catch((e) => {
    console.error('❌ Error seeding tax and shipping rates:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
