import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌍 Seeding currencies and languages...');

  // Seed currencies
  const currencies = [
    { code: 'USD', name: 'US Dollar', symbol: '$', rate: 1.000000, isDefault: true, decimals: 2, position: 'before' },
    { code: 'EUR', name: 'Euro', symbol: '€', rate: 0.850000, decimals: 2, position: 'before' },
    { code: 'GBP', name: 'British Pound', symbol: '£', rate: 0.730000, decimals: 2, position: 'before' },
    { code: 'JPY', name: 'Japanese Yen', symbol: '¥', rate: 110.000000, decimals: 0, position: 'before' },
    { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', rate: 6.450000, decimals: 2, position: 'before' },
    { code: 'INR', name: 'Indian Rupee', symbol: '₹', rate: 74.500000, decimals: 2, position: 'before' },
    { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', rate: 280.000000, decimals: 2, position: 'before' },
    { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', rate: 1.250000, decimals: 2, position: 'before' },
    { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', rate: 1.350000, decimals: 2, position: 'before' },
    { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', rate: 0.920000, decimals: 2, position: 'before' },
    { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', rate: 8.500000, decimals: 2, position: 'after' },
    { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', rate: 8.800000, decimals: 2, position: 'after' },
    { code: 'DKK', name: 'Danish Krone', symbol: 'kr', rate: 6.200000, decimals: 2, position: 'after' },
    { code: 'PLN', name: 'Polish Złoty', symbol: 'zł', rate: 3.800000, decimals: 2, position: 'after' },
    { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', rate: 21.500000, decimals: 2, position: 'after' },
    { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', rate: 300.000000, decimals: 0, position: 'after' },
    { code: 'RUB', name: 'Russian Ruble', symbol: '₽', rate: 75.000000, decimals: 2, position: 'after' },
    { code: 'TRY', name: 'Turkish Lira', symbol: '₺', rate: 8.500000, decimals: 2, position: 'before' },
    { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', rate: 5.200000, decimals: 2, position: 'before' },
    { code: 'MXN', name: 'Mexican Peso', symbol: '$', rate: 20.000000, decimals: 2, position: 'before' },
    { code: 'ARS', name: 'Argentine Peso', symbol: '$', rate: 95.000000, decimals: 2, position: 'before' },
    { code: 'CLP', name: 'Chilean Peso', symbol: '$', rate: 750.000000, decimals: 0, position: 'before' },
    { code: 'COP', name: 'Colombian Peso', symbol: '$', rate: 3800.000000, decimals: 0, position: 'before' },
    { code: 'PEN', name: 'Peruvian Sol', symbol: 'S/', rate: 4.000000, decimals: 2, position: 'before' },
    { code: 'UYU', name: 'Uruguayan Peso', symbol: '$', rate: 42.000000, decimals: 2, position: 'before' },
    { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', rate: 23000.000000, decimals: 0, position: 'after' },
    { code: 'THB', name: 'Thai Baht', symbol: '฿', rate: 32.500000, decimals: 2, position: 'before' },
    { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', rate: 4.150000, decimals: 2, position: 'before' },
    { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', rate: 1.350000, decimals: 2, position: 'before' },
    { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', rate: 7.800000, decimals: 2, position: 'before' },
    { code: 'KRW', name: 'South Korean Won', symbol: '₩', rate: 1100.000000, decimals: 0, position: 'before' },
    { code: 'TWD', name: 'Taiwan Dollar', symbol: 'NT$', rate: 28.000000, decimals: 2, position: 'before' },
    { code: 'PHP', name: 'Philippine Peso', symbol: '₱', rate: 50.000000, decimals: 2, position: 'before' },
    { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', rate: 14200.000000, decimals: 0, position: 'before' },
    { code: 'ZAR', name: 'South African Rand', symbol: 'R', rate: 14.500000, decimals: 2, position: 'before' },
    { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', rate: 15.700000, decimals: 2, position: 'before' },
    { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', rate: 410.000000, decimals: 2, position: 'before' },
    { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', rate: 108.000000, decimals: 2, position: 'before' },
    { code: 'GHS', name: 'Ghanaian Cedi', symbol: 'GH₵', rate: 6.000000, decimals: 2, position: 'before' },
    { code: 'MAD', name: 'Moroccan Dirham', symbol: 'MAD', rate: 9.000000, decimals: 2, position: 'before' },
    { code: 'TND', name: 'Tunisian Dinar', symbol: 'TND', rate: 2.800000, decimals: 3, position: 'before' },
    { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', rate: 3.670000, decimals: 2, position: 'before' },
    { code: 'SAR', name: 'Saudi Riyal', symbol: 'ر.س', rate: 3.750000, decimals: 2, position: 'before' },
    { code: 'QAR', name: 'Qatari Riyal', symbol: 'ر.ق', rate: 3.640000, decimals: 2, position: 'before' },
    { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', rate: 0.300000, decimals: 3, position: 'before' },
    { code: 'BHD', name: 'Bahraini Dinar', symbol: 'BD', rate: 0.376000, decimals: 3, position: 'before' },
    { code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.', rate: 0.385000, decimals: 3, position: 'before' },
    { code: 'JOD', name: 'Jordanian Dinar', symbol: 'د.ا', rate: 0.709000, decimals: 3, position: 'before' },
    { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل', rate: 1500.000000, decimals: 0, position: 'before' },
    { code: 'ILS', name: 'Israeli Shekel', symbol: '₪', rate: 3.200000, decimals: 2, position: 'before' },
    { code: 'IRR', name: 'Iranian Rial', symbol: 'ریال', rate: 42000.000000, decimals: 0, position: 'after' },
    { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', rate: 80.000000, decimals: 2, position: 'before' },
    { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', rate: 85.000000, decimals: 2, position: 'before' },
    { code: 'LKR', name: 'Sri Lankan Rupee', symbol: 'Rs', rate: 200.000000, decimals: 2, position: 'before' },
    { code: 'NPR', name: 'Nepalese Rupee', symbol: '₨', rate: 120.000000, decimals: 2, position: 'before' },
    { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', rate: 1600.000000, decimals: 0, position: 'before' },
    { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', rate: 4100.000000, decimals: 0, position: 'after' },
    { code: 'LAK', name: 'Lao Kip', symbol: '₭', rate: 9500.000000, decimals: 0, position: 'before' },
    { code: 'MNT', name: 'Mongolian Tögrög', symbol: '₮', rate: 2850.000000, decimals: 0, position: 'before' },
    { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', rate: 420.000000, decimals: 2, position: 'before' },
    { code: 'UZS', name: 'Uzbekistani Som', symbol: "so'm", rate: 10500.000000, decimals: 0, position: 'after' },
    { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'ЅМ', rate: 11.300000, decimals: 2, position: 'before' },
    { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'T', rate: 3.500000, decimals: 2, position: 'before' },
    { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', rate: 1.700000, decimals: 2, position: 'before' },
    { code: 'GEL', name: 'Georgian Lari', symbol: '₾', rate: 3.100000, decimals: 2, position: 'before' },
    { code: 'AMD', name: 'Armenian Dram', symbol: '֏', rate: 500.000000, decimals: 0, position: 'before' },
    { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', rate: 2.500000, decimals: 2, position: 'before' },
    { code: 'MDL', name: 'Moldovan Leu', symbol: 'L', rate: 17.800000, decimals: 2, position: 'before' },
    { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', rate: 27.000000, decimals: 2, position: 'before' },
    { code: 'RON', name: 'Romanian Leu', symbol: 'lei', rate: 4.200000, decimals: 2, position: 'after' },
    { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', rate: 1.650000, decimals: 2, position: 'after' },
    { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', rate: 6.300000, decimals: 2, position: 'after' },
    { code: 'RSD', name: 'Serbian Dinar', symbol: 'дин', rate: 100.000000, decimals: 0, position: 'after' },
    { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден', rate: 54.000000, decimals: 2, position: 'after' },
    { code: 'ALL', name: 'Albanian Lek', symbol: 'L', rate: 105.000000, decimals: 0, position: 'after' },
    { code: 'XCD', name: 'East Caribbean Dollar', symbol: 'EC$', rate: 2.700000, decimals: 2, position: 'before' },
    { code: 'BBD', name: 'Barbadian Dollar', symbol: 'B$', rate: 2.000000, decimals: 2, position: 'before' },
    { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$', rate: 150.000000, decimals: 2, position: 'before' },
    { code: 'TTD', name: 'Trinidad and Tobago Dollar', symbol: 'TT$', rate: 6.800000, decimals: 2, position: 'before' },
    { code: 'BZD', name: 'Belize Dollar', symbol: 'BZ$', rate: 2.000000, decimals: 2, position: 'before' },
    { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', rate: 7.700000, decimals: 2, position: 'before' },
    { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', rate: 24.000000, decimals: 2, position: 'before' },
    { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$', rate: 35.000000, decimals: 2, position: 'before' },
    { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', rate: 620.000000, decimals: 0, position: 'before' },
    { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', rate: 1.000000, decimals: 2, position: 'before' },
    { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs', rate: 6.900000, decimals: 2, position: 'before' },
    { code: 'PYG', name: 'Paraguayan Guaraní', symbol: '₲', rate: 6800.000000, decimals: 0, position: 'before' },
    { code: 'GYD', name: 'Guyanese Dollar', symbol: 'G$', rate: 208.000000, decimals: 2, position: 'before' },
    { code: 'SRD', name: 'Surinamese Dollar', symbol: '$', rate: 21.000000, decimals: 2, position: 'before' },
    { code: 'FJD', name: 'Fijian Dollar', symbol: 'FJ$', rate: 2.100000, decimals: 2, position: 'before' },
    { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', rate: 3.500000, decimals: 2, position: 'before' },
    { code: 'WST', name: 'Samoan Tālā', symbol: 'T', rate: 2.600000, decimals: 2, position: 'before' },
    { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$', rate: 2.300000, decimals: 2, position: 'before' },
    { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT', rate: 110.000000, decimals: 0, position: 'before' },
    { code: 'SBD', name: 'Solomon Islands Dollar', symbol: 'SI$', rate: 8.000000, decimals: 2, position: 'before' },
    { code: 'KID', name: 'Kiribati Dollar', symbol: '$', rate: 1.350000, decimals: 2, position: 'before' },
    { code: 'TVD', name: 'Tuvaluan Dollar', symbol: '$', rate: 1.350000, decimals: 2, position: 'before' },
    { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', rate: 1.400000, decimals: 2, position: 'before' },
  ];

  for (const currency of currencies) {
    await prisma.currencyConfig.upsert({
      where: { code: currency.code },
      update: currency,
      create: currency,
    });
  }

  console.log(`✅ Seeded ${currencies.length} currencies`);

  // Seed languages
  const languages = [
    { code: 'en', name: 'English', nativeName: 'English', isDefault: true, isRTL: false },
    { code: 'es', name: 'Spanish', nativeName: 'Español', isRTL: false },
    { code: 'fr', name: 'French', nativeName: 'Français', isRTL: false },
    { code: 'de', name: 'German', nativeName: 'Deutsch', isRTL: false },
    { code: 'it', name: 'Italian', nativeName: 'Italiano', isRTL: false },
    { code: 'pt', name: 'Portuguese', nativeName: 'Português', isRTL: false },
    { code: 'ru', name: 'Russian', nativeName: 'Русский', isRTL: false },
    { code: 'zh', name: 'Chinese', nativeName: '中文', isRTL: false },
    { code: 'ja', name: 'Japanese', nativeName: '日本語', isRTL: false },
    { code: 'ko', name: 'Korean', nativeName: '한국어', isRTL: false },
    { code: 'ar', name: 'Arabic', nativeName: 'العربية', isRTL: true },
    { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', isRTL: false },
    { code: 'ur', name: 'Urdu', nativeName: 'اردو', isRTL: true },
    { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', isRTL: false },
    { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', isRTL: false },
    { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', isRTL: false },
    { code: 'mr', name: 'Marathi', nativeName: 'मराठी', isRTL: false },
    { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', isRTL: false },
    { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', isRTL: false },
    { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', isRTL: false },
    { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', isRTL: false },
    { code: 'or', name: 'Oriya', nativeName: 'ଓଡ଼ିଆ', isRTL: false },
    { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া', isRTL: false },
    { code: 'sd', name: 'Sindhi', nativeName: 'سنڌي', isRTL: true },
    { code: 'ks', name: 'Kashmiri', nativeName: 'कॉशुर', isRTL: false },
    { code: 'ne', name: 'Nepali', nativeName: 'नेपाली', isRTL: false },
    { code: 'si', name: 'Sinhala', nativeName: 'සිංහල', isRTL: false },
    { code: 'th', name: 'Thai', nativeName: 'ไทย', isRTL: false },
    { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', isRTL: false },
    { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', isRTL: false },
    { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu', isRTL: false },
    { code: 'fil', name: 'Filipino', nativeName: 'Filipino', isRTL: false },
    { code: 'my', name: 'Burmese', nativeName: 'မြန်မာ', isRTL: false },
    { code: 'km', name: 'Khmer', nativeName: 'ខ្មែរ', isRTL: false },
    { code: 'lo', name: 'Lao', nativeName: 'ລາວ', isRTL: false },
    { code: 'mn', name: 'Mongolian', nativeName: 'Монгол', isRTL: false },
    { code: 'kk', name: 'Kazakh', nativeName: 'Қазақ', isRTL: false },
    { code: 'uz', name: 'Uzbek', nativeName: "O'zbek", isRTL: false },
    { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', isRTL: false },
    { code: 'az', name: 'Azerbaijani', nativeName: 'Azərbaycan', isRTL: false },
    { code: 'ka', name: 'Georgian', nativeName: 'ქართული', isRTL: false },
    { code: 'hy', name: 'Armenian', nativeName: 'Հայերեն', isRTL: false },
    { code: 'fa', name: 'Persian', nativeName: 'فارسی', isRTL: true },
    { code: 'ku', name: 'Kurdish', nativeName: 'کوردی', isRTL: true },
    { code: 'he', name: 'Hebrew', nativeName: 'עברית', isRTL: true },
    { code: 'el', name: 'Greek', nativeName: 'Ελληνικά', isRTL: false },
    { code: 'bg', name: 'Bulgarian', nativeName: 'Български', isRTL: false },
    { code: 'mk', name: 'Macedonian', nativeName: 'Македонски', isRTL: false },
    { code: 'sr', name: 'Serbian', nativeName: 'Српски', isRTL: false },
    { code: 'hr', name: 'Croatian', nativeName: 'Hrvatski', isRTL: false },
    { code: 'sl', name: 'Slovenian', nativeName: 'Slovenščina', isRTL: false },
    { code: 'sk', name: 'Slovak', nativeName: 'Slovenčina', isRTL: false },
    { code: 'cs', name: 'Czech', nativeName: 'Čeština', isRTL: false },
    { code: 'pl', name: 'Polish', nativeName: 'Polski', isRTL: false },
    { code: 'hu', name: 'Hungarian', nativeName: 'Magyar', isRTL: false },
    { code: 'ro', name: 'Romanian', nativeName: 'Română', isRTL: false },
    { code: 'sq', name: 'Albanian', nativeName: 'Shqip', isRTL: false },
    { code: 'et', name: 'Estonian', nativeName: 'Eesti', isRTL: false },
    { code: 'lv', name: 'Latvian', nativeName: 'Latviešu', isRTL: false },
    { code: 'lt', name: 'Lithuanian', nativeName: 'Lietuvių', isRTL: false },
    { code: 'fi', name: 'Finnish', nativeName: 'Suomi', isRTL: false },
    { code: 'sv', name: 'Swedish', nativeName: 'Svenska', isRTL: false },
    { code: 'no', name: 'Norwegian', nativeName: 'Norsk', isRTL: false },
    { code: 'da', name: 'Danish', nativeName: 'Dansk', isRTL: false },
    { code: 'is', name: 'Icelandic', nativeName: 'Íslenska', isRTL: false },
    { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', isRTL: false },
    { code: 'be', name: 'Belgian', nativeName: 'Vlaams', isRTL: false },
    { code: 'lb', name: 'Luxembourgish', nativeName: 'Lëtzebuergesch', isRTL: false },
    { code: 'gsw', name: 'Swiss German', nativeName: 'Schwiizertüütsch', isRTL: false },
    { code: 'ca', name: 'Catalan', nativeName: 'Català', isRTL: false },
    { code: 'eu', name: 'Basque', nativeName: 'Euskara', isRTL: false },
    { code: 'gl', name: 'Galician', nativeName: 'Galego', isRTL: false },
    { code: 'cy', name: 'Welsh', nativeName: 'Cymraeg', isRTL: false },
    { code: 'gd', name: 'Scottish Gaelic', nativeName: 'Gàidhlig', isRTL: false },
    { code: 'ga', name: 'Irish', nativeName: 'Gaeilge', isRTL: false },
    { code: 'gv', name: 'Manx', nativeName: 'Gaelg', isRTL: false },
    { code: 'kw', name: 'Cornish', nativeName: 'Kernewek', isRTL: false },
    { code: 'br', name: 'Breton', nativeName: 'Brezhoneg', isRTL: false },
    { code: 'oc', name: 'Occitan', nativeName: 'Occitan', isRTL: false },
    { code: 'pro', name: 'Provençal', nativeName: 'Provençau', isRTL: false },
    { code: 'co', name: 'Corsican', nativeName: 'Corsu', isRTL: false },
    { code: 'sc', name: 'Sardinian', nativeName: 'Sardu', isRTL: false },
    { code: 'scn', name: 'Sicilian', nativeName: 'Sicilianu', isRTL: false },
    { code: 'nap', name: 'Neapolitan', nativeName: 'Napulitano', isRTL: false },
    { code: 'vec', name: 'Venetian', nativeName: 'Vèneto', isRTL: false },
    { code: 'lmo', name: 'Lombard', nativeName: 'Lumbaart', isRTL: false },
    { code: 'pms', name: 'Piedmontese', nativeName: 'Piemontèis', isRTL: false },
    { code: 'lij', name: 'Ligurian', nativeName: 'Lìgure', isRTL: false },
    { code: 'egl', name: 'Emilian', nativeName: 'Emiliàn', isRTL: false },
    { code: 'rgn', name: 'Romagnol', nativeName: 'Rumagnòl', isRTL: false },
    { code: 'tus', name: 'Tuscan', nativeName: 'Toscano', isRTL: false },
    { code: 'umb', name: 'Umbrian', nativeName: 'Umbro', isRTL: false },
    { code: 'mrc', name: 'Marchegian', nativeName: 'Marchigiano', isRTL: false },
    { code: 'ab', name: 'Abruzzese', nativeName: 'Abruzzese', isRTL: false },
    { code: 'mol', name: 'Molise', nativeName: 'Molisano', isRTL: false },
    { code: 'apu', name: 'Apulian', nativeName: 'Pugliese', isRTL: false },
    { code: 'cal', name: 'Calabrian', nativeName: 'Calabrese', isRTL: false },
  ];

  for (const language of languages) {
    await prisma.languageConfig.upsert({
      where: { code: language.code },
      update: language,
      create: language,
    });
  }

  console.log(`✅ Seeded ${languages.length} languages`);

  console.log('🎉 Currency and language seeding completed!');
}

main()
  .catch((e) => {
    console.error('❌ Error seeding currencies and languages:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
